import type { Metadata } from 'next';
import { Playfair, IBM_Plex_Mono, Inter } from 'next/font/google';
import { GoogleAnalytics } from '@next/third-parties/google';
import { GoogleTagManager } from '@next/third-parties/google';

import './globals.css';

const playfair = Playfair({
  subsets: ['latin'],
  variable: '--font-playfair',
});

const ibmPlexMono = IBM_Plex_Mono({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-ibm-plex-mono',
});

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`
         ${playfair.variable} ${ibmPlexMono.variable} ${inter.variable} h-full antialiased`}
    >
      <GoogleTagManager gtmId="GTM-T4BGX8JC" />
      <body className="min-h-full flex flex-col">{children}</body>
      {/* <GoogleAnalytics gaId="GTM-T4BGX8JC" /> */}
    </html>
  );
}
